### PR TITLE
Try pytest-nunit with azure pipelines

### PR DESCRIPTION
**Pull request by tonybaloney**
Try an alpha version with nunit XML 
Cc @zooba

### CODE REVIEW

**Comment by tonybaloney** [comment]
do you have the PR hooks setup? am not seeing a build being kicked off?

**Comment by zooba** [comment]
Apparently it's not hooked up...

**Comment by zooba** [comment]
There we go @tonybaloney - I had to check the "allow build from forks" option.

**Comment by zooba** [comment]
Freaked out because I saw I'd been ignoring a pull request on this repo, and then saw it was just this one 😆

I'm assuming it's out of date now, so going to close it so I can achieve PR Inbox Zero and not stress myself next time!

**Pull request closed without merging**
